### ISSUE TITLE
Updated to Xamarin.Forms.1.3.3.6323 and Acr.XamForms.UserDialogs.3.0.1

### ISSUE THREAD

**Issue by StephanPatrick** [aritchie/acr-xamarin-forms#82]
Hi have updated the Acr.XamForms.UserDialogs.3.0.0 to the Acr.XamForms.UserDialogs.3.0.1 and update Xamarin.Forms.1.3.1.6296 to Xamarin.Forms.1.3.3.6323 and I have this trouble during compilation :

error : Cannot resolve dependency to assembly 'Xamarin.Forms.Core, Version=1.3.2.0, Culture=neutral, PublicKeyToken=null' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the  ReflectionOnlyAssemblyResolve event.

On Android and IOS the update is Ok.

**Comment by aritchie** [comment]
I don't have the time to deploy updates for every xamarin forms release.  If you don't want to wait for the updates, clone the repo and do it yourself.

**Comment by shabeepk** [comment]
Great. It would be very kind of you if you can let us know how to do it? Or may be provide a link that tells us how to do it. So we can do it ourselves whenever required?

**Comment by aritchie** [comment]
@shabeepk - no offence, but I'm not here to provide .NET compilation 101.  I'm happy to help with defects or feature requests, but this goes outside of what I'm willing to do unless I'm being contracted as a consultant.  

The basic 4 steps to up this are: Clone this github repo, update the nuget libraries, compile, take dlls and put them into your project.

**Comment by shabeepk** [comment]
@aritchie Thanks for the advice, even though I've already done that. I wasn't actually talking about compiling the project, I was talking about publishing the nuget.

Anyway,

I can still help by exporting the nugets built for 1.3.3 and send them to you so you can publish them whenever you'd like. Otherwise it is all fine.

Thanks.

**Comment by shabeepk** [comment]
I can see you've published the new version.

Thanks.

One possible solution to this issue you are facing that you have to publish a new version for every Xamarin minor release is that you do not mention the Xamarin.Forms version upto to minor part. That may ease a lot of pain for you. So instead of mentioning 

``` [1.3.3.6323, 2.0) ```

in the nuspec you should mention 

```[1.3.3, 2.0) ```

that would make your nuget packages to at least build in most cases. Obviously Xamarin won't make API level changes in a minor release so that should always work for you.

Just thought I should let you know as the build I made myself I built it this way and it was working flawlessly.

Thanks.

**Comment by aritchie** [comment]
The build # makes no difference.  The problem isn't to do with nuget.  It is to do with the fact that windows phone is grabbing a hard version to a specific xamarin.forms version.

**Comment by shabeepk** [comment]
Ahan, Okay Thanks for the info.
