### ISSUE TITLE
UserDialogs progress runs backward

### ISSUE THREAD

**Issue by alexrainman** [aritchie/acr-xamarin-forms#89]
First time i run progress dialog it shows the progress in a strange way. It doesn't shows in blue. It shows the progress already filled in grey and start showing the progress in white/transparent. Any ideas?

**Comment by aritchie** [comment]
I'm not really sure what you're asking me.  
Why do you expect the progress to show up in blue?  
What is strange besides the default grey?
What platform is this on?
Screenshots, code, any additional details?

**Comment by alexrainman** [comment]
Hi, I'm sorry for not giving you more details. I'm using same code from your demo. Let me upload a video so you can see what i'm talking about. Platform iOS. Video: https://drive.google.com/file/d/0B6hZDQudMRBUOEw5TFNvQWlVdFE/view?usp=sharing

**Comment by aritchie** [comment]
I don't understand why you think this is strange behaviour?  It looks like it works fine in your video.

**Comment by alexrainman** [comment]
The first time the progress is full grey and start showing the progress in transparent, second time the progress is not visible and start showing the progress in blue ...

**Comment by aritchie** [comment]
The only thing I can see in the video is that the loading area is changing color which isn't a big issue.  This could be a timing thing.  You kill one loader and then instantly start up another and the animation could still be running.  

This isn't really a problem with the colors.  It adapts to the background I believe.  Put a timed break so that the animation can finish or reset the same loader to start the second load.
